### ISSUE TITLE
Invite to OpenMMLab Talk~

### ISSUE THREAD

**Issue by vansinhu** [xdxie/WordArt#11]
Hello Xudong Xie,

我是OpenMMLab的运营闻星。

冒昧打扰，我们关注到你们的最新工作“Toward Understanding WordArt: Corner-Guided Transformer for Scene Text Recognition”非常精彩，进而希望通过邮件与您取得联系。
目前我们社区也在筹备文字识别相关领域的顶会专题分享，您的论文工作中正好也使用了OpenMMLab中的MMOCR算法库，非常希望邀请您也参与其中，开展相关分享。

在此，我先向您简单介绍一下我们社区及线上分享的相关活动。

OpenMMLab 诞生于 2018 年，是深度学习时代计算机视觉领域最全面、最具影响力的开源算法体系。旨在为学术和产业界提供一个可跨方向、结构精良、跨站性强、易复现的统一算法工具库。目前，OpenMMLab 已经累计开源了超过 30 个算法库，涵盖分类、检测、分割、视频理解等众多算法领域，有超过 300 种算法实现、2,400 多个预训练模型。在 GitHub 上获得超过 75,000 个标星，同时吸引了超过 1,600 名社区开发者参与项目贡献，用户遍及超过 110 个国家和地区，覆盖全国全球顶尖高校、研究机构和企业。

社区开放麦是由OpenMMLab发起，面向所有AI领域用户开放的直播栏目，旨在搭建一个知识分享舞台。内容多元设计顶会分享、源码解读、圆桌讨论等。迄今为止已经举办超过40期，观看人数超过40,000人，视频回放超过420,000次。近期OpenMMLab联合ReadPaper、将门创投、白云兰开源联合开启学术专题分享。围绕前沿进展、学术热点特邀顶会作者参与分享。

期待您的回复

我的微信是 van-sin

**Comment by xdxie** [comment]
您好！十分感谢OpenMMLab的邀请，我很愿意进行本次分享，贵社区之前发我的邮件我已回复，谢谢！
