### ISSUE TITLE
可视化Visualization

### ISSUE THREAD

**Issue by YangShuang66** [xdxie/WordArt#17]
您好，我在阅读了您发表的论文后，受益匪浅。请问论文中提到的  编码器输出的特征图可视化代码  具体在哪个文件夹下呀？希望能够向您请教。
Hello, I greatly benefited from reading your published paper. Could you please tell me in which folder the code for visualizing the feature maps from the encoder output is located? I would like to seek your guidance on this matter.

**Comment by xudongxie688** [comment]
请参考这条回答 https://github.com/xdxie/WordArt/issues/8#issuecomment-1432488061

**Comment by xdxie** [comment]
请参考之前的问题 https://github.com/xdxie/WordArt/issues/8#issuecomment-1432488061
