### ISSUE TITLE
self attention module for Xg' in paper

### ISSUE THREAD

**Issue by yeyoe** [xdxie/WordArt#3]
It was a great paper that really inspired me. But I have a question about the detail.
In the paper, there is a self attention module before Cross-Attention. But in this code, I can't find this. Is it not important for the result?

**Comment by xdxie** [comment]
Thanks! The code has implemented the "self-attention + cross-attention" module in corner_crossattn_layers.py:
https://github.com/xdxie/WordArt/blob/cc1dae78ed924dae2ab8b4001edbc483f9caae4c/mmocr/models/textrecog/layers/corner_crossattn_layers.py#L38

I'm sorry that the naming of this module gave you a misunderstanding.
