### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by Qingkali** [xdxie/WordArt#4]
When I train you model and meet thr problem :lmdb.Error: UniformConcatDataset: OCRDataset: AnnFileLoader: data/mixture/Syn90k/label.lmdb: No such file or directory.
Could you help me fix the problem? Thanks.

**Comment by xdxie** [comment]
You can follow [https://mmocr.readthedocs.io/en/v0.6.1/datasets/recog.html](this document) to prepare the datasets. Our code is based on MMOCR 0.6, the training datasets need to be preprocessed.
