### ISSUE TITLE
Can you provide the training weights about CornerTransformer?

### ISSUE THREAD

**Issue by Yullj** [xdxie/WordArt#5]
Hello! I am very interested in CornerTransformer. Could you provide me with a way to download the training weights about CornerTransformer?

**Comment by xdxie** [comment]
You can download the model by this link: https://drive.google.com/file/d/11FsyGxtvGPPvh9TXOVZDHqr6HlGdWDmZ/view?usp=sharing
Different evaluation runtime environments may result in some deviation in the final results.

**Comment by ShashankKrishnaV** [comment]
Where is the configs file which I can use to train the model?
