### ISSUE TITLE
运行环境问题

### ISSUE THREAD

**Issue by ld835** [xdxie/WordArt#6]
作者你好，我想问下运行此代码最少需要多大内存？我云主机有14g的内存在SynthText数据集生成裁剪后的图像标注和代码训练时都killed了

**Comment by xdxie** [comment]
一般需要4卡V100，如果您只有14g内存的话，需要将batchsize调到很小

**Comment by ld835** [comment]
> 一般需要4卡V100，如果您只有14g内存的话，需要将batchsize调到很小

好的好的谢谢
