### ISSUE TITLE
求注意力可视化的相关代码

### ISSUE THREAD

**Issue by zisang0210** [xdxie/WordArt#8]
您好！论文中解码器输出特征图可视化的效果非常好，请问可以公开下相关代码吗？或说明下图片是怎么生成的？感谢！

**Comment by xdxie** [comment]
您好，论文中的可视化是针对encoder最后的输出特征图做的，做法比较简单，可以直接把特征图输入这个函数，沿着C通道求平均即可

`def visulize_all_channel_into_one(self, feature_map, i):
        output = feature_map

        output = output.data.squeeze()
        output = output.cpu().numpy()

        output = np.mean(output, axis=0)

        height, width = 32, 128
        times = height / float(width)
        plt.rcParams["figure.figsize"] = (1, times)
        plt.axis('off')
        plt.imshow(output, cmap='jet', interpolation='bilinear')
        plt.savefig('vis/{}.png'.format(i), dpi=3 * height)`

**Comment by YangShuang66** [comment]
> 您好，论文中的可视化是针对encoder最后的输出特征图做的，做法比较简单，可以直接把特征图输入这个函数，沿着C通道求平均即可
> 
> `def visulize_all_channel_into_one(self, feature_map, i):         output = feature_map
> 
>         output = output.data.squeeze()         output = output.cpu().numpy()
> 
>         output = np.mean(output, axis=0)
> 
>         height, width = 32, 128         times = height / float(width)         plt.rcParams["figure.figsize"] = (1, times)         plt.axis('off')         plt.imshow(output, cmap='jet', interpolation='bilinear')         plt.savefig('vis/{}.png'.format(i), dpi=3 * height)`

作者你好，编码器的输出是（N，T，D_m）其中N是batch_size,T是H*W，D_m是隐藏层维度，这是一个二维数据。
如何沿通道维度求平均呢
